name: lint

on: push

jobs:
  lint-and-format-python-code:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyproject-flake8 black
      - name: Format by black
        run: |
          black .
      - name: Commit files
        continue-on-error: true
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "format by black" .
          git push
      - name: Check by flake8
        run: |
          pflake8 --count --show-source --statistics .